version: "3.8"

services:
  app:
    build:
      context: ./
      shm_size: "4gb"
      args:
        USER_UID: ${HOST_UID:-1000}
        USER_GID: ${HOST_GID:-1000}
    tty: true
    volumes:
      - ./:/workspace/repo:cached
    ports:
      - "8000:8000"
    environment:
      TZ: Asia/Tokyo
      NVIDIA_VISIBLE_DEVICES: all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
